//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetsFightCovid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerReview
    {
        public int customer_ID { get; set; }
        public string customer_name { get; set; }
        public string customer_email { get; set; }
        public string customer_address { get; set; }
        public string customer_review { get; set; }
    }
}
