//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetsFightCovid.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LetsFightCovidEntities : DbContext
    {
        public LetsFightCovidEntities()
            : base("name=LetsFightCovidEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminMember> AdminMembers { get; set; }
        public virtual DbSet<Ambulance> Ambulances { get; set; }
        public virtual DbSet<Hospital> Hospitals { get; set; }
        public virtual DbSet<Icu> Icus { get; set; }
        public virtual DbSet<OxygenProvider> OxygenProviders { get; set; }
        public virtual DbSet<Plasma> Plasmas { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VaccinationCenter> VaccinationCenters { get; set; }
    }
}
