//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetsFightCovid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Icu
    {
        public int icu_ID { get; set; }
        public Nullable<int> icu_availability { get; set; }
        public string cost_per_day { get; set; }
        public Nullable<int> hospital_ID { get; set; }
    
        public virtual Hospital Hospital { get; set; }
    }
}
