//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetsFightCovid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Img
    {
        public int id { get; set; }
        public string iname { get; set; }
        public Nullable<int> pid { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
