//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetsFightCovid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plasma
    {
        public int plasma_ID { get; set; }
        public string donor_name { get; set; }
        public string donor_address { get; set; }
        public string blood_group { get; set; }
        public string donor_contact { get; set; }
        public int plasma_availability { get; set; }
    }
}
