//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetsFightCovid.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class User
    {
        public int users_ID { get; set; }

        [System.ComponentModel.DataAnnotations.Required(ErrorMessage ="This field is Required")]
        [System.ComponentModel.DataAnnotations.Display(Name="Full Name")]
        public string full_name { get; set; }

        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "This field is Required")]
        [System.ComponentModel.DataAnnotations.Display(Name = "Age")]
        public int age { get; set; }

        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "This field is Required")]
        [System.ComponentModel.DataAnnotations.Display(Name = "Contact No.")]
        public string contact { get; set; }

        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "This field is Required")]
        [System.ComponentModel.DataAnnotations.Display(Name = "Email")]
        public string email { get; set; }

        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "This field is Required")]
        [System.ComponentModel.DataAnnotations.Display(Name = "Address")]
        public string full_address { get; set; }

        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "This field is Required")]
        [System.ComponentModel.DataAnnotations.Display(Name = "Username")]
        public string userName { get; set; }

        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "This field is Required")]
        [System.ComponentModel.DataAnnotations.Display(Name = "Password")]
        public string passwords { get; set; }

        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = "This field is Required")]
        [System.ComponentModel.DataAnnotations.Display(Name = "Confirm Password")]
        [NotMapped]
        [Compare("passwords",ErrorMessage ="Confirm Password doesn't match,type again!")]
        public string Repasswords { get; set; }
    }
}
