//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetsFightCovid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaccinationCenter
    {
        public int center_ID { get; set; }
        public string hospital_name { get; set; }
        public string center_location { get; set; }
        public string available_vaccine { get; set; }
    }
}
